In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,-1],[1,4,5],[1,4,1]])
A

array([[ 1,  2, -1],
       [ 1,  4,  5],
       [ 1,  4,  1]])

In [3]:
def getv(A, i):
    n,m = A.shape
    I = np.eye(n)
    a = np.zeros(n)
    
    a[i:] = A[i:,i]
#     print("a"+str(i))
#     print(a)
    
    norm = np.sqrt(sum((a[:]**2)))
    
    v = a + norm * I[:,i]
    v = v[:,None]
#     print("v"+str(i))
#     print(v)
    return v

In [4]:
def getH(A,i):
    n,m = A.shape
    I = np.eye(n)
        
    v = getv(A,i)
    H = I - 2/(v.T@v)*(v@v.T)
#     print("H"+st(i))
#     print(H)
    return H
    

In [5]:
def getqr(A):
    n,m = A.shape
    R = A.copy()
    Q = np.eye(n)
    
    for i in range(n-1):
        H = getH(R,i)
        R = H@R
        Q = Q@H
#         print("R"+str(i))
#         print(R)

    return Q, R
        

In [6]:
Q, R = getqr(A)
print("Z mojej funkcji:")
print("Q:\n",np.round(Q,5))
print("R:\n",np.round(R, 5))

Z mojej funkcji:
Q:
 [[-0.57735  0.8165  -0.     ]
 [-0.57735 -0.40825 -0.70711]
 [-0.57735 -0.40825  0.70711]]
R:
 [[-1.73205 -5.7735  -2.88675]
 [ 0.      -1.63299 -3.26599]
 [ 0.       0.      -2.82843]]


In [7]:
q, r = np.linalg.qr(A)
print("Z funkcji wbudowanej:")
print("Q:\n",np.round(q,5))
print("R:\n",np.round(r, 5))

Z funkcji wbudowanej:
Q:
 [[-0.57735  0.8165  -0.     ]
 [-0.57735 -0.40825 -0.70711]
 [-0.57735 -0.40825  0.70711]]
R:
 [[-1.73205 -5.7735  -2.88675]
 [ 0.      -1.63299 -3.26599]
 [ 0.       0.      -2.82843]]
